// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamSystem.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    partial class SchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ders", b =>
                {
                    b.Property<string>("DersKodu")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MuellimAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MuellimSoyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sinifi")
                        .HasColumnType("int");

                    b.HasKey("DersKodu");

                    b.ToTable("Dərslər");
                });

            modelBuilder.Entity("Imtahan", b =>
                {
                    b.Property<int>("ImtahanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImtahanID"));

                    b.Property<string>("DersKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ImtahanTarixi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Qiymeti")
                        .HasColumnType("int");

                    b.Property<int>("SagirdNomresi")
                        .HasColumnType("int");

                    b.HasKey("ImtahanID");

                    b.HasIndex("DersKodu");

                    b.HasIndex("SagirdNomresi");

                    b.ToTable("İmtahanlar");
                });

            modelBuilder.Entity("Sagird", b =>
                {
                    b.Property<int>("Nomresi")
                        .HasColumnType("int");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sinifi")
                        .HasColumnType("int");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Nomresi");

                    b.ToTable("Şagirdlər");
                });

            modelBuilder.Entity("Imtahan", b =>
                {
                    b.HasOne("Ders", "Ders")
                        .WithMany()
                        .HasForeignKey("DersKodu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sagird", "Sagird")
                        .WithMany()
                        .HasForeignKey("SagirdNomresi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Sagird");
                });
#pragma warning restore 612, 618
        }
    }
}
